### ISSUE TITLE
Add link to 'nestest.nes'

### ISSUE THREAD

**Issue by jesusrp98** [OneLoneCoder/olcNES#11]
In the latest video, you use a nes ROM to test some emulator functionality. 

Could you provide a link to that ROM file?

**Comment by miniragnarok** [comment]
He covered that in Part 2. It's on this page.
http://wiki.nesdev.com/w/index.php/Emulator_tests

It's under CPU tests and is called nestest.

**Comment by jesusrp98** [comment]
Thank you very much!
