### ISSUE TITLE
I don't understand how SBC works

### ISSUE THREAD

**Issue by Cheaterman** [OneLoneCoder/olcNES#24]
https://github.com/OneLoneCoder/olcNES/blob/4dbe2e752d28008f2b28140822605901742366e3/Part%232%20-%20CPU/olc6502.cpp#L697

You wrote:
`A = A - M - (1 - C) = A + -1 * (M - (1 - C)) = A + (-M + 1 + C)`

Possibly two mistakes here - first is, `A - M - (1 - C)` factors to `A + -1M + -1(1 - C) = A + -1(M + (1 - C))`  IMHO?
Second, if I try the last part myself, I get `A + -1 * (M + -1(1 - C)) = A + -1 * (M + -1 + C) = A - M + 1 - C`

If I try from scratch, I get:
`A = A - M - (1 - C) = A - M - 1 + C = A + C + -1 * (M + 1) = A + C - M - 1`

Alternatively:
`A = A - M - (1 - C) = A + -1M + -1(1 - C) = A + -1 (M + (1-C)) = A + -1 (M + 1 - C) = A - M - 1 + C`

(both results equivalent to `A+C-M-1`)

Is there something I'm misunderstanding there?

I mean, I'm not doubting your code works fine (in fact, seeing Duck Tales run, I'm pretty sure it does...), but maybe the explanation of WHY it runs is slightly inaccurate?

**Comment by Cheaterman** [comment]
Actually I think I understand why it works: even given my result `A+C-M-1`, you could refactor as `A + C + -1 * (M + 1)`, and if I invert M's bits I essentially get `-1(M + 1)` because of two's complement, which is why you simply XOR `M` in your code?

**Comment by Cheaterman** [comment]
Ah, someone already caught that in the comments to the video: https://www.youtube.com/watch?v=8XmxKPJDGU0&lc=UgyksS0M8MSuTahlLv94AaABAg :-)

**Comment by Cheaterman** [comment]
Okay, but given all of this, I have a problem with this line:
https://github.com/OneLoneCoder/olcNES/blob/master/Part%232%20-%20CPU/olc6502.cpp#L727
Isn't this doing `(R^A) & (R^M)` instead of `~(A^M) & (A^R)` ?

**Comment by qdirks** [comment]
@Cheaterman
I was having trouble with this too, but I finally figured it out. I'll try to explain.

So, there's more than one way to determine if the overflow flag should be set. One way is how OLC did it for the ADC instruction, which is `~(A^M) & (A^R) & 0x80`. In words, if A and M are the same, and A is different to R, and both binary terms have bit 0x80 active (the sign bit), then an overflow has occurred.

There is another way, which the OLC has apparently used for the SBC instruction, and that is `(R^A) & (R^M) & 0x80`. In words, if A is different to R, and M is different to R, and both binary terms have bit 0x80 active (the sign bit), then an overflow has occurred.

It's just slightly different ways of saying the same thing. Personally, I like the second way better because it uses 1 less character. Following is how I wrote my ADC and SBC:

```
uint8_t olc6502::ADC()
{
    fetch();
    uint8_t value = fetched;
    uint16_t temp = a + value + GetFlag(C);
    SetFlag(C, temp & 0xff00);                  // Set C if any bits were carried out.
    SetFlag(Z, (temp & 0xff) == 0);             // Set Z if the low byte is equal to 0.
    SetFlag(N, temp & 0x80);                    // Set N if the sign bit is on.
    SetFlag(V, (temp^a) & (temp^value) & 0x80); // Set V if the sign of the result is
                                                // different than the sign of A and M.
    a = temp;
    return 1;
}

uint8_t olc6502::SBC()
{
    fetch();
    uint8_t value = ~fetched;

    // now continuing exactly the same as addition:

    uint16_t temp = a + value + GetFlag(C);
    SetFlag(C, temp & 0xff00);
    SetFlag(Z, (temp & 0xff) == 0);
    SetFlag(N, temp & 0x80);
    SetFlag(V, (temp^a) & (temp^value) & 0x80);
    a = temp;
    return 1;
}
```

**Comment by Cheaterman** [comment]
Pretty cool, thanks! This explains that! I checked the truth table Javidx9 made, and it all adds up pretty well indeed (or rather XOR's up :stuck_out_tongue: ).

I ended up abstracting away all add/substract operations to a single function (same for the repetitive branching code), this is how it all looks like now:

```cython
    cdef bint ADC(self):
        return self.add(self.fetch())

    cdef bint SBC(self):
        return self.add(self.fetch() ^ 0xFF)

    cdef bint add(self, unsigned char value):
        cdef unsigned char a_value, result
        a_value = self.a
        result = a_value + value + self.status.flags.C
        self.status.flags.C = <bint>(result > 0xFF)
        self.status.flags.Z = <bint>(result & 0xFF == 0)
        self.status.flags.V = <bint>((a_value ^ result) & ~(a_value ^ value) & 0x80)
        self.status.flags.N = <bint>(result & 0x80)
        self.a = result & 0xFF
        return True
```

(Excuse the language BTW, this is Cython :-) )
